CREATE DATABASE IF NOT EXISTS pwa_project CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pwa_project;

CREATE TABLE IF NOT EXISTS vijesti (
  id INT AUTO_INCREMENT PRIMARY KEY,
  datum VARCHAR(32) NOT NULL,
  naslov VARCHAR(255) NOT NULL,
  sazetak TEXT NOT NULL,
  tekst TEXT NOT NULL,
  slika VARCHAR(255) DEFAULT NULL,
  kategorija VARCHAR(50) NOT NULL,
  arhiva TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS korisnik (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ime VARCHAR(64) NOT NULL,
  prezime VARCHAR(64) NOT NULL,
  korisnicko_ime VARCHAR(64) NOT NULL UNIQUE,
  lozinka VARCHAR(255) NOT NULL,
  razina TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


